import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import { getCoffeeStore } from "../lib/coffee-store";
import styles from "../styles/Home.module.css";

export async function getStaticProps(context) {
  let coffeestore = [];
  try {
    coffeestore = await getCoffeeStore(28.74866467846766, 77.04733444406916);
  } catch (e) {
    console.log("error", e);
  }
  return {
    props: {
      coffeestore,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const bannerClickHandler = () => {
    console.log("Button clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner text="Find nearby shops" onClickHandler={bannerClickHandler} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" height={400} width={700} />
        </div>
        {props.coffeestore.length > 0 && (
          <>
            <h2 className={styles.heading2}>Delhi Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeestore.map((store) => (
                <Card
                  name={store.name}
                  href={`/coffee-store/${store.id}`}
                  imgUrl={store.imgUrl}
                  key={store.id}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
