import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";

export default function Home() {
  const bannerClickHandler = () => {
    console.log("Button clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner text="Find nearby shops" onClickHandler={bannerClickHandler} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" height={400} width={700} />
        </div>
      </main>
    </div>
  );
}
